# Site settings
title: "Chaeyeon Chung"
# description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Chaeyeon Chung"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "chaeyeonc@nvidia.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "chaeyeonc[at]nvidia[dot]com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Hi, I am a Research Engineer at NVIDIA Digital Human Technology, currently focusing on Audio2Face. I earned PhD at Kim Jaechul Graduate School of Artificial Intelligence, Korea Advanced Institute of Science and Technology (KAIST), advised by Prof. Jaegul Choo.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/cychungg"
  resume_linkedin_url:          "https://www.linkedin.com/in/chaeyeonchung"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
